web: 
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ../projects:/projects
    - ./nginx-conf:/etc/nginx/conf.d
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ../projects:/projects
